defaultPortal: NTP-2.0-DEV
portals:
  - name: NTP-2.0-DEV
    portalId: 45046299
    env: prod
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CPm96rmAMhIOAAUAQAAAAGwAQAJYAgEYm7S9FSD_zIAeKO7pDDIUmx5uQv_DfMTPqqfhuN_GRN3tEuc6TAAABEEAAAAAAAAAAAAAAAAAgAAAAAAABAAAAAAAAAAAPGBQAABEAABA_BgGABAgAwAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAABBCFA3qrDDfTwgkiC8LMZ7WI17gE_JsSgNuYTFSAFoAYAA
        expiresAt: '2024-06-11T12:16:40.739Z'
    accountType: STANDARD
    personalAccessKey: >-
      CiQzMWQyYTMyNy0xZjc3LTRhM2ItYjUyNy0zNjAzYmUyMWY3OGEQm7S9FRj_zIAeKhkABeaRgnxkHhEwqiWR3nkL71Ali6lstIL5SgNuYTE
